In [1]:
import torch
import numpy as np

In [3]:
print("=" * 60)
print("Part 1: Creating Tensors from Data")
print("=" * 60)

# create tensors with ... dim
scalar = torch.tensor(7)
print(f"Scalar: {scalar}")
print(f"Scalar: {scalar.ndim}")

vector = torch.tensor([1, 2, 3, 4, 5])
print(f"\nVector: {vector}")
print(f"Vector shape: {vector.shape}")

matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"\nMatrix:\n{matrix}")
print(f"Matrix shape: {matrix.shape}")

tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"\n3D Tensor:\n{tensor_3d}")
print(f"3D Tensor shape: {tensor_3d.shape}")


Scalar: 7
Scalar: 0

Vector: tensor([1, 2, 3, 4, 5])
Vector shape: torch.Size([5])

Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])
Matrix shape: torch.Size([2, 3])

3D Tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
3D Tensor shape: torch.Size([2, 2, 2])


In [24]:
print("\n" + "=" * 60)
print("Part 2: Creating Tensors with Specific Values")
print("=" * 60)

zeros = torch.zeros(3, 4)
print(f"Zero (3x4): \n{zeros}")

ones = torch.ones(2, 3)
print(f"\nOne (2x3): \n{ones}")

full = torch.full((2, 3), 7)
print(f"\nFull with 7s (2x3): \n{full}")

identity = torch.eye(4)
print(f"\nIdentity matrix (4x4):\n{identity}")

range_tensor = torch.arange(0, 10)
print(f"\nRange (0-9):\n{range_tensor}")

linspace = torch.linspace(0,10, steps=7)
print(f"\nLinspace (0-10, 7 steps):\n{linspace}")


Zero (3x4): 
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

One (2x3): 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Full with 7s (2x3): 
tensor([[7, 7, 7],
        [7, 7, 7]])

Identity matrix (4x4):
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

Range (0-9):
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Linspace (0-10, 7 steps):
tensor([ 0.0000,  1.6667,  3.3333,  5.0000,  6.6667,  8.3333, 10.0000])


In [40]:
print("\n" + "=" * 60)
print("Part 3: Creating Random Tensors")
print("=" * 60)
torch.manual_seed(42)

rand_uniform = torch.rand(3, 4)
print(f"Random uniform (3x4):\n{rand_uniform}")

rand_normal = torch.randn(2, 3)
print(f"\nRandom normal (2x3):\n{rand_normal}")

rand_int = torch.randint(low=0, high=10, size=(3, 3))
print(f"\nRandom integers (0-9, 3x3):\n{rand_int}")

Random uniform (3x4):
tensor([[0.6315, 0.8352, 0.9929, 0.4234],
        [0.6038, 0.1525, 0.3970, 0.8703],
        [0.7563, 0.1836, 0.0991, 0.1583]])

Random normal (2x3):
tensor([[ 0.1395,  0.0477, -0.8571],
        [-1.5483,  2.2143,  0.3455]])

Random integers (0-9, 3x3):
tensor([[3, 4, 9],
        [8, 3, 4],
        [2, 4, 1]])


In [49]:
print("\n" + "=" * 60)
print("Part 4: Working with NumPy")
print("=" * 60)

np_array = np.array([[1, 2, 3], [4, 5, 6]])
print(f"NumPy array:\n{np_array}")

tensor_from_np = torch.from_numpy(np_array)
print(f"\nTensor from NumPy:\n{tensor_from_np}")

np_from_tensor = tensor_from_np.numpy()
print(f"\nNumPy from tensor:\n{np_from_tensor}")


NumPy array:
[[1 2 3]
 [4 5 6]]

Tensor from NumPy:
tensor([[1, 2, 3],
        [4, 5, 6]])

NumPy from tensor:
[[1 2 3]
 [4 5 6]]


In [62]:
tensor = torch.randn(2,3,4)
print({tensor})
tensor.shape, tensor.ndim, tensor.dtype, tensor.numel()

{tensor([[[ 0.1268, -2.4521,  0.4160,  1.9025],
         [-1.3525, -0.1303,  1.7551,  0.0675],
         [-0.0510,  1.4310,  0.3673, -0.0192]],

        [[-1.0667, -1.9893,  0.2973,  0.4345],
         [-1.4201, -0.5559,  1.6862,  0.9885],
         [ 1.3676, -0.3197, -0.9131,  1.9192]]])}


(torch.Size([2, 3, 4]), 3, torch.float32, 24)

----**Exercises**------


In [83]:
# Exercise 1: Create a 4x4 tensor filled with the value 3.14
print("\nExercise 1: Create a 4x4 tensor filled with 3.14")
torch.full((4, 4), 3.14)


Exercise 1: Create a 4x4 tensor filled with 3.14


tensor([[3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400]])

In [82]:
# Exercise 2: Create a random tensor of shape (5, 5) with values between 0 and 1
torch.manual_seed(42)
print("\nExercise 2: Create random 5x5 tensor [0, 1)")
torch.rand(5,5)


Exercise 2: Create random 5x5 tensor [0, 1)


tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317, 0.1053]])

In [79]:
# Exercise 3: Create a tensor with values from 10 to 50 (exclusive) with step 5
print("\nExercise 3: Range from 10 to 50 with step 5")
torch.arange(10, 50, 5)


Exercise 3: Range from 10 to 50 with step 5


tensor([10, 15, 20, 25, 30, 35, 40, 45])

In [73]:
# Exercise 4: Create a 3D tensor of shape (2, 3, 4) filled with ones
print("\nExercise 4: Create 3D tensor (2, 3, 4) of ones")
torch.ones(2,3,4)


Exercise 4: Create 3D tensor (2, 3, 4) of ones


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [77]:
# Exercise 5: Check if a GPU is available and create a tensor on it if possible
print("\nExercise 5: Create tensor on GPU if available")
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"{device}")
tensor = torch.tensor([1,2,3]).to(device)
tensor.device


Exercise 5: Create tensor on GPU if available
cpu


device(type='cpu')

In [78]:
#for cleaner device management
if torch.cuda.is_available():
    # Set CUDA as the default device
    torch.set_default_device('cuda')

    # All subsequent tensors are created on CUDA by default
    x_auto = torch.randn(2, 3)
    print(f"Auto-created on device: {x_auto.device}")

    # Reset to CPU
    torch.set_default_device('cpu')
    y_auto = torch.randn(2, 3)
    print(f"Reset to CPU device: {y_auto.device}")

In [81]:
print("\n" + "=" * 60)
print("Exercise 1 Complete!")
print("=" * 60)


Exercise 1 Complete!
