In [3]:
import torch
torch.manual_seed(42)

In [6]:
print("=" * 60)
print("Part 1: Basic Arithmetic Operations")
print("=" * 60)

# Create test tensors
x = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
y = torch.tensor([5, 6, 7, 8], dtype=torch.float32)

print(f"x: {x}")
print(f"y: {y}")

Part 1: Basic Arithmetic Operations
x: tensor([1., 2., 3., 4.])
y: tensor([5., 6., 7., 8.])


In [8]:
add_result = x + y
print(f"\nAddition (x + y): {add_result}")

#
sub_result = x - y
print(f"Subtraction (x - y): {sub_result}")

#
mul_result = x * y
print(f"Multiplication (x * y): {mul_result}")

#
div_result = x / y
print(f"Division (x / y): {div_result}")

#
pow_result = x ** 2
print(f"Power (x^2): {pow_result}")


Addition (x + y): tensor([ 6.,  8., 10., 12.])
Subtraction (x - y): tensor([-4., -4., -4., -4.])
Multiplication (x * y): tensor([ 5., 12., 21., 32.])
Division (x / y): tensor([0.2000, 0.3333, 0.4286, 0.5000])
Power (x^2): tensor([ 1.,  4.,  9., 16.])


In [16]:
print("\n" + "=" * 60)
print("Part 2: Matrix Operations")
print("=" * 60)

# Create matrices
A = torch.randn(3, 4)
B = torch.randn(4, 5)

print(f"Matrix A shape: {A.shape}")
print(f"Matrix B shape: {B.shape}")

A, B, A.dtype, B.dtype, A.ndim, B.ndim


Part 2: Matrix Operations
Matrix A shape: torch.Size([3, 4])
Matrix B shape: torch.Size([4, 5])


(tensor([[-0.7723,  0.1532,  1.3270, -0.8024],
         [ 2.9246, -0.7985, -0.5669, -0.0267],
         [-1.5460, -2.1799,  0.2074, -1.9844]]),
 tensor([[ 0.1954, -1.3350,  0.3945,  1.7060, -0.2184],
         [ 0.1663,  2.1442,  1.7046,  0.3459,  0.6425],
         [-0.2040,  0.6854, -0.1397, -1.1808, -1.2829],
         [ 0.4485, -0.5907,  0.8541, -0.4901, -0.3595]]),
 torch.float32,
 torch.float32,
 2,
 2)

In [22]:
#  Matrix multiplication
matmul_result = A @ B
print(f"\nMatrix multiplication A @ B shape: {matmul_result.shape}")

# Transpose
A_T = A.T
print(f"Transpose of A shape: {A_T.shape}")

#
min_val = torch.min(A)
max_val = torch.max(A)
print(f"\nMin value in A: {min_val:.4f}")
print(f"Max value in A: {max_val:.4f}")


Matrix multiplication A @ B shape: torch.Size([3, 5])
Transpose of A shape: torch.Size([4, 3])

Min value in A: -2.1799
Max value in A: 2.9246


In [27]:
print("\n" + "=" * 60)
print("Part 3: Reduction Operations")
print("=" * 60)

# Create a 2D tensor
tensor = torch.randn(3, 4)
print(f"Tensor:\n{tensor}")
tensor.ndim


Part 3: Reduction Operations
Tensor:
tensor([[-1.6004,  0.8984, -0.6497,  0.2194],
        [ 0.5447, -2.0567,  0.2344, -0.3407],
        [ 1.0171,  1.1458, -0.0556, -0.3598]])


2

In [33]:
sum_all = torch.sum(tensor)
print(f"\nSum of all elements: {sum_all:.4f}")

sum_rows = torch.sum(tensor, dim=0)
print(f"Sum along rows: {sum_rows}")

sum_cols = torch.sum(tensor, dim=1)
print(f"Sum along columns: {sum_cols}")

mean_all = torch.mean(tensor)
print(f"\nMean of all elements: {mean_all:.4f}")
#Standard deviation
std_all = torch.std(tensor)
print(f"Standard deviation: {std_all:.4f}")


Sum of all elements: -1.0031
Sum along rows: tensor([-0.0385, -0.0126, -0.4709, -0.4812])
Sum along columns: tensor([-1.1324, -1.6183,  1.7475])

Mean of all elements: -0.0836
Standard deviation: 0.9969


In [82]:
print("\n" + "=" * 60)
print("Part 4: Comparison Operations")
print("=" * 60)

x = torch.tensor([1,2,3,4,5])
y = torch.tensor([2, 2, 4, 4, 6])

print(f"x: {x}")
print(f"y: {y}")

# TODO: Element-wise comparison
eq_result = x == y
print(f"\nEqual (x == y): {eq_result}")

gt_result = x > y
print(f"Greater than (x > y): {gt_result}")

lt_result = x < y
print(f"Less than (x < y): {lt_result}")

clamped = torch.clamp(x, min=1, max=3)
print(f"\nClamp x to [1, 3]: {clamped}")


Part 4: Comparison Operations
x: tensor([1, 2, 3, 4, 5])
y: tensor([2, 2, 4, 4, 6])

Equal (x == y): tensor([False,  True, False,  True, False])
Greater than (x > y): tensor([False, False, False, False, False])
Less than (x < y): tensor([ True, False,  True, False,  True])

Clamp x to [1, 3]: tensor([1, 2, 3, 3, 3])


In [50]:
print("\n" + "=" * 60)
print("Part 5: Broadcasting")
print("=" * 60)

x = torch.randn(4,1)
y = torch.randn(1,6)
print(f"x shape: {x.shape}")
print(f"y shape: {y.shape}")

result = x + y
print(f"\nBroadcast result shape: {result.shape}")
print(f"Result:\n{result}")


Part 5: Broadcasting
x shape: torch.Size([4, 1])
y shape: torch.Size([1, 6])

Broadcast result shape: torch.Size([4, 6])
Result:
tensor([[-0.2036,  0.8453,  2.7262,  1.3521,  2.2563,  0.6433],
        [-1.1541, -0.1052,  1.7757,  0.4016,  1.3058, -0.3071],
        [-2.1967, -1.1479,  0.7330, -0.6410,  0.2632, -1.3498],
        [-0.7345,  0.3143,  2.1953,  0.8212,  1.7254,  0.1124]])


In [64]:
print("\n" + "=" * 60)
print("Exercises")
print("=" * 60)

# Exercise 1: Given two matrices A (4x3) and B (3x5), compute C = A @ B
A = torch.randn(4, 3)
B = torch.randn(3, 5)
C = A @ B
print(f"\nMatrix multiplication A @ B shape: {C.shape}")
A_T = A.T
D = torch.randn(4, 6)
E = torch.matmul(A_T, D)
print(f"\nMatrix multiplication A_T @ D shape: {E.shape}")



Exercises

Matrix multiplication A @ B shape: torch.Size([4, 5])

Matrix multiplication A_T @ D shape: torch.Size([3, 6])


In [63]:
# Exercise 2: Normalize a tensor to have zero mean and unit variance
print("\nExercise 2: Normalize tensor")
tensor = torch.randn(100, 10)
mean_tensor = torch.mean(tensor)
print(f"Mean of tensor: {mean_tensor:.4f}")
std_tensor = torch.std(tensor)
print(f"Standard deviation of tensor: {std_tensor:.4f}")
normalized_tensor = (tensor - mean_tensor) / std_tensor
print(f"\nNormalized tensor has {normalized_tensor.ndim} dimension and the shape: {normalized_tensor.shape}")



Exercise 2: Normalize tensor
Mean of tensor: 0.0609
Standard deviation of tensor: 0.9816

Normalized tensor has 2 dimension and the shape: torch.Size([100, 10])


In [67]:
# Exercise 3: Find the indices of the top 3 values in a tensor
print("\nExercise 3: Find top 3 indices")

tensor = torch.randn(10)

values, indices = torch.topk(tensor, k=3)
print(f"Original tensor: {tensor}")
print(f"Top 3 values: {values}")
print(f"Top 3 indices: {indices}")



Exercise 3: Find top 3 indices
Original tensor: tensor([ 0.3453, -0.0228,  1.1068,  0.9151, -1.0930, -0.3718, -2.6464,  1.1614,
         0.9581, -0.7093])
Top 3 values: tensor([1.1614, 1.1068, 0.9581])
Top 3 indices: tensor([7, 2, 8])


In [78]:
# Exercise 4: Implement softmax function
print("\nExercise 4: Implement softmax")
logits = torch.randn(2, 5)
#makes postive and amplifies diff
exp_logits = torch.exp(logits)
print(f"Logits:\n{logits}")
print(f"Exp Logits:\n{exp_logits}")
#Probabilities
softmax = exp_logits / torch.sum(exp_logits, dim=1, keepdim=True)
print(f"\nSoftmax:\n{softmax}")

print(f"\nSum per row: {softmax.sum(dim=1)}")
#Verify the ans
verify = torch.nn.functional.softmax(logits, dim=1)
print(f"\nVerify Softmax:\n{torch.allclose(softmax, verify)}")



Exercise 4: Implement softmax
Logits:
tensor([[-2.1419,  0.3842, -1.8046, -0.0033, -0.5576],
        [-0.0764, -0.9294,  1.7773, -1.0220,  0.2654]])
Exp Logits:
tensor([[0.1174, 1.4684, 0.1645, 0.9967, 0.5726],
        [0.9265, 0.3948, 5.9137, 0.3599, 1.3039]])

Softmax:
tensor([[0.0354, 0.4423, 0.0496, 0.3002, 0.1725],
        [0.1041, 0.0444, 0.6646, 0.0404, 0.1465]])

Sum per row: tensor([1., 1.])

Verify Softmax:
True


In [90]:
# Exercise 5: Compute cosine similarity between two vectors
print("\nExercise 5: Cosine similarity")
v1 = torch.randn(100)
v2 = torch.randn(100)
print(f"Compute cosine")
cosine_similarity = torch.dot(v1, v2) / (torch.linalg.norm(v1) * torch.linalg.norm(v2))
print(f"Cosine similarity: {cosine_similarity:.4f}")


Exercise 5: Cosine similarity
Compute cosine
Cosine similarity: 0.0158


In [77]:
print("\n" + "=" * 60)
print("Exercise 2 Complete!")
print("=" * 60)


Exercise 2 Complete!
