In [1]:
import torch
torch.manual_seed(42)

In [2]:
print("=" * 60)
print("Part 1: Reshaping Tensors")
print("=" * 60)

Part 1: Reshaping Tensors


In [3]:
# Create a 1D tensor
x = torch.arange(12)
print(f"Original tensor: {x}")
print(f"Original shape: {x.shape}")

#  Reshape to 3x4
reshaped = x.reshape(3, 4)
print(f"\nReshaped to (3, 4):\n{reshaped}")

#  Reshape to 2x6
reshaped_2x6 = x.reshape(2, 6)
print(f"\nReshaped to (2, 6):\n{reshaped_2x6}")

#  Flatten a 2D tensor
flat = reshaped.flatten()
print(f"\nFlattened: {flat}")

#  Reshape with view (only works on contiguous tensors)
viewed = reshaped.view(-1)  # -1 means infer dimension
print(f"\nViewed as 1D: {viewed}")

Original tensor: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Original shape: torch.Size([12])

Reshaped to (3, 4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Reshaped to (2, 6):
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

Flattened: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Viewed as 1D: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [4]:
print("\n" + "=" * 60)
print("Part 2: Squeeze and Unsqueeze")
print("=" * 60)

x = torch.randn(2, 1, 4, 3, 1, 5)
print(f"Original shape: {x.shape}")

#  Remove all singleton dimensions
squeezed = x.squeeze()
print(f"After squeeze: {squeezed.shape}")

#  Remove specific singleton dimension
squeezed_dim = x.squeeze(dim=1)
print(f"After squeeze(dim=1): {squeezed_dim.shape}")

#  Add dimension at position 0
unsqueezed_0 = squeezed.unsqueeze(dim=0)
print(f"\nAfter unsqueeze(dim=0): {unsqueezed_0.shape}")

#  Add dimension at last position
unsqueezed_last = squeezed.unsqueeze(dim=-1)
print(f"After unsqueeze(dim=-1): {unsqueezed_last.shape}")



Part 2: Squeeze and Unsqueeze
Original shape: torch.Size([2, 1, 4, 3, 1, 5])
After squeeze: torch.Size([2, 4, 3, 5])
After squeeze(dim=1): torch.Size([2, 4, 3, 1, 5])

After unsqueeze(dim=0): torch.Size([1, 2, 4, 3, 5])
After unsqueeze(dim=-1): torch.Size([2, 4, 3, 5, 1])


In [5]:
print("\n" + "=" * 60)
print("Part 3: Transpose and Permute")
print("=" * 60)

x = torch.randn(2, 3, 4)
print(f"Original shape: {x.shape}")

transposed = torch.transpose(x, 0, 1)
print(f"After transpose(0, 1): {transposed.shape}")

permuted = x.permute(2, 0, 1)
print(f"After permute(2, 0, 1): {permuted.shape}")

matrix = torch.randn(3, 4)
print(f"\nMatrix shape: {matrix.shape}")
print(f"Matrix.T shape: {matrix.T.shape}")


Part 3: Transpose and Permute
Original shape: torch.Size([2, 3, 4])
After transpose(0, 1): torch.Size([3, 2, 4])
After permute(2, 0, 1): torch.Size([4, 2, 3])

Matrix shape: torch.Size([3, 4])
Matrix.T shape: torch.Size([4, 3])


In [14]:
print("\n" + "=" * 60)
print("Part 4: Indexing and Slicing")
print("=" * 60)

x = torch.arange(20).reshape(4, 5)
print("tensor: ", x)

element = x[2, 4]
print(f"\nElement at [2, 4]: {element}")

#  Get first row
first_row = x[0, :]
print(f"\nFirst row: {first_row}")

#  Get last column
last_col = x[:, -1]
print(f"Last column: {last_col}")

submatrix = x[2:4, 3:5]
print(f"\nSubmatrix:\n{submatrix}")

mask = x > 10
values = x[mask]
print(f"\nValues > 10: {values}")



Part 4: Indexing and Slicing
tensor:  tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

Element at [2, 4]: 14

First row: tensor([0, 1, 2, 3, 4])
Last column: tensor([ 4,  9, 14, 19])

Submatrix:
tensor([[13, 14],
        [18, 19]])

Values > 10: tensor([11, 12, 13, 14, 15, 16, 17, 18, 19])


In [7]:
print("\n" + "=" * 60)
print("Part 5: Concatenating and Splitting")
print("=" * 60)

# Create tensors to concatenate
x1 = torch.randn(2, 3)
x2 = torch.randn(2, 3)
x3 = torch.randn(2, 3)
print(f"x1 shape: {x1.shape}")
print(f"x2 shape: {x2.shape}")

stacked = torch.stack([x1,x2,x3], dim=0)
print(f"\nStacked along dim=0: {stacked.shape}")

concat_dim0 = torch.cat([x1,x2,x3], dim=0)
print(f"Concatenated along dim=0: {concat_dim0.shape}")

x = torch.randn(6, 4)
chunks = torch.chunk(x, chunks=3, dim=0)
print(f"\nSplit into 3 chunks along dim=0:")
for i, chunk in enumerate(chunks):
    print(f"  Chunk {i} shape: {chunk.shape}")

split_sections = torch.split(x, [2, 4], dim=0)
print(f"\nSplit into sections of size [2, 4]:")
for i, section in enumerate(split_sections):
    print(f"  Section {i} shape: {section.shape}")




Part 5: Concatenating and Splitting
x1 shape: torch.Size([2, 3])
x2 shape: torch.Size([2, 3])

Stacked along dim=0: torch.Size([3, 2, 3])
Concatenated along dim=0: torch.Size([6, 3])

Split into 3 chunks along dim=0:
  Chunk 0 shape: torch.Size([2, 4])
  Chunk 1 shape: torch.Size([2, 4])
  Chunk 2 shape: torch.Size([2, 4])

Split into sections of size [2, 4]:
  Section 0 shape: torch.Size([2, 4])
  Section 1 shape: torch.Size([4, 4])


In [8]:
print("\n" + "=" * 60)
print("Exercises")
print("=" * 60)

# Exercise 1: Given a tensor of shape (64, 1, 28, 28), remove the singleton dimension
print("\nExercise 1: Remove singleton dimension")
x = torch.randn(64, 1, 28, 28)
squeezed_x = torch.squeeze(x, dim=1)
squeezed_x.shape


Exercises

Exercise 1: Remove singleton dimension


torch.Size([64, 28, 28])

In [9]:
# Exercise 2: Add a batch dimension to a single image tensor of shape (3, 224, 224)
print("\nExercise 2: Add batch dimension")
image = torch.randn(3, 224, 224)
unsqueezed_img = torch.unsqueeze(image, dim=0)
unsqueezed_img.shape


Exercise 2: Add batch dimension


torch.Size([1, 3, 224, 224])

In [10]:
# Exercise 3: Convert HWC format to CHW format
print("\nExercise 3: HWC to CHW conversion")
hwc_image = torch.randn(224, 224, 3)
# chw_image = torch.transpose(hwc_image , 0, 2)
# print(chw_image.shape)
#test
chw_image = hwc_image.permute(2, 0, 1)
print(chw_image.shape)


Exercise 3: HWC to CHW conversion
torch.Size([3, 224, 224])


In [11]:
# Exercise 4: Extract the diagonal elements from a square matrix
print("\nExercise 4: Extract diagonal")
matrix = torch.randn(5, 5)
print(matrix)
diagonal = torch.diag(matrix)
print(f"Diagonal elements: {diagonal}")


Exercise 4: Extract diagonal
tensor([[-0.9498,  0.0578,  0.0782, -1.2702,  2.3511],
        [ 2.6098,  0.4824, -0.4544,  0.1981, -0.8562],
        [-0.5732,  0.9958, -0.6068,  1.3357,  0.4433],
        [ 1.0543,  2.9158, -3.0199, -0.8459, -0.6839],
        [-0.4324, -1.6649,  0.8990, -2.2273,  0.0687]])
Diagonal elements: tensor([-0.9498,  0.4824, -0.6068, -0.8459,  0.0687])


In [12]:
# Exercise 5: Create a batch of 10 random images and stack them
print("\nExercise 5: Stack images into batch")
images = [torch.randn(3, 224, 224) for _ in range(10)]

batch = torch.stack(images, dim=0)
print(batch.shape)


Exercise 5: Stack images into batch
torch.Size([10, 3, 224, 224])


In [13]:
print("\n" + "=" * 60)
print("Exercise 3 Complete!")
print("=" * 60)



Exercise 3 Complete!
